/** Generated English glosses for the supplied B1 vocabulary list. */
export const B1_MEANINGS: Record<string, string> = {
  "abdecken": "cover",
  "abdrehen": "turn off",
  "Abfall": "Waste",
  "Abflug": "Departure",
  "Abgas": "exhaust",
  "abhängig": "dependent",
  "abheften": "file away",
  "abnehmen": "lose weight",
  "Absage": "Cancellation",
  "abschicken": "send",
  "absichtlich": "intentionally",
  "absolvieren": "complete",
  "absprechen": "agree",
  "Abstellplatz": "parking space",
  "Abteilungsleiter/in": "Head of department",
  "Abwasser": "Sewage",
  "abwechslungsreich": "varied",
  "Abwicklung": "Processing",
  "achten": "pay attention",
  "AGB": "Terms and Conditions",
  "aktiv": "active",
  "akzeptieren": "accept",
  "Alkohol": "Alcohol",
  "allerdings": "however",
  "Allergie": "allergy",
  "allergisch": "allergic",
  "Alliierte": "Allies",
  "Altenpfleger/in": "Geriatric nurse",
  "Alter": "Dude",
  "Altöl": "Waste oil",
  "Altpapier": "Waste paper",
  "Aluminium": "Aluminum",
  "amtlich": "official",
  "Amtssprache": "Official language",
  "Anbau": "Cultivation",
  "andauernd": "constantly",
  "anerkennen": "acknowledge",
  "Anerkennung": "Recognition",
  "anfahren": "drive off",
  "Anfang": "beginning",
  "anfangs": "initially",
  "anfassen": "touch",
  "angenehm": "pleasant",
  "angewöhnen": "get into the habit",
  "anheben": "lift",
  "ankündigen": "announce",
  "Anlage": "Facility",
  "anmachen": "turn on",
  "Annahme": "Acceptance",
  "annulliert": "cancelled",
  "Anprobe": "Fitting",
  "anprobieren": "try on",
  "anrechnen": "credit",
  "anschauen": "look at",
  "ansehen": "view",
  "anstatt": "instead",
  "ansteckend": "contagious",
  "Anstellung": "Employment",
  "Anstoß": "Kickoff",
  "anstreichen": "paint",
  "anstrengend": "tiring",
  "Anzeigetafel": "Scoreboard",
  "Arbeitskraft": "Workforce",
  "Arbeitslosigkeit": "Unemployment",
  "Arbeitsstelle": "workplace",
  "Arbeitsweise": "Way of working",
  "Arbeitszeit": "Working time",
  "Ärger": "Trouble",
  "ärgerlich": "annoying",
  "Art": "Art",
  "Artikelnummer": "Item number",
  "ärztlich": "medical",
  "Assistenz": "Assistance",
  "Astronaut/in": "Astronaut",
  "Asyl": "Asylum",
  "Atmung": "Breathing",
  "atmungsaktiv": "breathable",
  "aufdrehen": "turn it up",
  "aufkommen": "arise",
  "aufmachen": "open up",
  "aufmerksam": "attentive",
  "Aufregung": "Excitement",
  "Aufruf": "Call",
  "aufschreiben": "write down",
  "aufteilen": "divide",
  "Aufteilung": "Division",
  "Auftrag": "Order",
  "Auftragsnummer": "Order number",
  "auseinandersetzen": "deal with",
  "Ausgang": "exit",
  "ausgewogen": "balanced",
  "ausliefern": "deliver",
  "Ausnahme": "Exception",
  "ausparken": "park out",
  "ausprobieren": "try it out",
  "ausschalten": "turn off",
  "ausschlafen": "sleep in",
  "Außenspiegel": "Exterior mirror",
  "Ausstattung": "Equipment",
  "ausstellen": "exhibit",
  "Auswahl": "Selection",
  "Auswanderer": "Emigrants",
  "Auswanderung": "Emigration",
  "Auszug": "Excerpt",
  "Autofahrer/in": "Driver",
  "Automarke": "Car brand",
  "Autorennen": "Car racing",
  "Autoteil": "Auto part",
  "Autoversicherung": "Car insurance",
  "Bachelor": "Bachelor",
  "Balkongeländer": "Balcony railing",
  "Bankeinzug": "Bank debit",
  "Bearbeitung": "Editing",
  "bedenklich": "worrying",
  "Bedingung": "Condition",
  "befestigen": "attach",
  "befragen": "question",
  "begeistern": "inspire",
  "beglaubigen": "certify",
  "Beglaubigung": "Certification",
  "Begleitperson": "accompanying person",
  "behalten": "keep",
  "Behälter": "container",
  "behaupten": "claim",
  "beherrschen": "master",
  "beilegen": "attach",
  "Bekannte": "acquaintances",
  "belasten": "burden",
  "Belastung": "burden",
  "beleidigen": "insult",
  "Beleidigung": "insult",
  "beliebt": "popular",
  "benötigen": "need",
  "Benzin": "Gasoline",
  "beobachten": "observe",
  "berechtigt": "entitled",
  "bereits": "already",
  "berufen": "appointed",
  "Berufsbezeichnung": "Job title",
  "Berufserfahrung": "Work experience",
  "Berufsleben": "professional life",
  "Berufstätigkeit": "professional activity",
  "Besatzungszone": "occupation zone",
  "beschädigen": "damage",
  "beschädigt": "damaged",
  "bescheinigen": "certify",
  "beschimpfen": "insult",
  "Beschimpfung": "insult",
  "beschweren": "complain",
  "besiegen": "defeat",
  "Besprechungszimmer": "Meeting room",
  "Bestellhotline": "Order hotline",
  "Betrag": "amount",
  "betreten": "enter",
  "Betriebswirtschaft": "Business Administration",
  "betrunken": "drunk",
  "beurteilen": "assess",
  "Beutel": "pouch",
  "Bevölkerung": "population",
  "Bewerbungsschreiben": "Application letter",
  "Bewohner/in": "resident",
  "bewusst": "consciously",
  "Bezahlvorgang": "Payment process",
  "Biergarten": "Beer garden",
  "Bilanzbuchhalter/in": "Accountant",
  "bio": "bio",
  "biologisch": "biological",
  "Bioprodukt": "Organic product",
  "bisher": "so far",
  "Blinker": "Blinker",
  "bloß": "just",
  "Blumentopf": "flower pot",
  "bohren": "drill",
  "Bordkarte": "Boarding pass",
  "Boxen": "Boxing",
  "bremsen": "brake",
  "Briefpapier": "stationery",
  "Bundeskanzler/in": "Federal Chancellor",
  "Bundesrepublik": "Federal Republic",
  "Bürger/in": "citizen",
  "Bürgerkrieg": "Civil War",
  "Büroalltag": "Office life",
  "Büroassistent/in": "Office assistant",
  "Büromaterial": "Office supplies",
  "Büroraum": "Office space",
  "Bürozeit": "Office time",
  "Callcenter": "Call center",
  "Camper/in": "Camper",
  "Campingplatz": "Campsite",
  "Catering": "Catering",
  "Check-in-Schalter": "Check-in counter",
  "Chemikalie": "chemical",
  "Chips": "Chips",
  "Container": "Containers",
  "Dach": "roof",
  "daneben": "next to it",
  "Datenschutz": "Data protection",
  "Deckel": "Lid",
  "demnächst": "soon",
  "Demokratie": "Democracy",
  "demokratisch": "democratic",
  "Demonstration": "demonstration",
  "deswegen": "that's why",
  "Detektivgeschichte": "Detective story",
  "DDR": "GDR",
  "Diabetiker/in": "Diabetic",
  "Diagramm": "Diagram",
  "dicht": "close",
  "Diebstahl": "Theft",
  "Dienstleistung": "Service",
  "Dienstreise": "Business trip",
  "Diskussion": "Discussion",
  "Dokumentation": "Documentation",
  "Döner": "Doner kebab",
  "doof": "stupid",
  "Doppelbett": "Double bed",
  "doppelt": "double",
  "Doppelzimmer": "Double room",
  "Dorf": "Village",
  "dramatisch": "dramatic",
  "sein": "be",
  "drinnen": "inside",
  "dumm": "stupid",
  "durchlässig": "permeable",
  "Durchschnitt": "Average",
  "durchschnittlich": "average",
  "DVD": "DVD",
  "ebenso": "likewise",
  "ehemalig": "former",
  "eher": "rather",
  "ehrlich": "honestly",
  "Eierkarton": "Egg carton",
  "Eierschale": "Eggshell",
  "Eigentum": "property",
  "eigenverantwortlich": "self-responsible",
  "eilig": "hastily",
  "einbrechen": "break in",
  "Einbrecher/in": "Burglar",
  "Einbruch": "Burglary",
  "einchecken": "check in",
  "einfallen": "occur",
  "einführen": "introduce",
  "eingehen": "enter",
  "einhalten": "comply",
  "Einkommen": "Income",
  "einlegen": "insert",
  "einparken": "park",
  "einreichen": "submit",
  "einschalten": "turn on",
  "einschlafen": "fall asleep",
  "einschreiben": "enroll",
  "einseitig": "one-sided",
  "einsetzen": "insert",
  "einsperren": "lock up",
  "Einsteigezeit": "Boarding time",
  "einstellen": "set",
  "Eintrittsdatum": "Entry date",
  "Einwanderung": "Immigration",
  "Einzelzimmer": "Single room",
  "Eishockey": "Ice hockey",
  "Eiskunstlauf": "Figure skating",
  "Eiweiß": "Protein",
  "Elektroauto": "Electric car",
  "emotional": "emotional",
  "Empfang": "Reception",
  "empfangen": "received",
  "enden": "end",
  "Energiekosten": "Energy costs",
  "Energiesparhaus": "Energy saving house",
  "Energiesparlampe": "Energy saving lamp",
  "Energieverschwendung": "Waste of energy",
  "englischsprachig": "English speaking",
  "entnehmen": "remove",
  "Entscheidung": "decision",
  "entspannend": "relaxing",
  "entsprechen": "correspond",
  "entstehen": "arise",
  "enttäuschen": "disappoint",
  "Enttäuschung": "Disappointment",
  "entwickeln": "develop",
  "Erdbeben": "Earthquake",
  "Erde": "Earth",
  "Erderwärmung": "Global warming",
  "Ereignis": "event",
  "erfolgreich": "successful",
  "Ergänzung": "Supplement",
  "Ergebnis": "Result",
  "Erhalt": "receipt",
  "erhältlich": "available",
  "erhöhen": "increase",
  "erinnern": "remember",
  "Erinnerung": "Memory",
  "erkennen": "recognize",
  "Erklärung": "explanation",
  "erkundigen": "inquire",
  "Erlaubnis": "permission",
  "erleben": "experience",
  "erleichtern": "facilitate",
  "ernähren": "feed",
  "Ernährung": "Nutrition",
  "Erstellung": "Creation",
  "erwähnen": "mention",
  "eskalieren": "escalate",
  "Esser/in": "eater",
  "Euroeinführung": "Euro introduction",
  "Union": "Union",
  "eventuell": "possibly",
  "exotisch": "exotic",
  "Experte/Expertin": "Expert",
  "Fähigkeit": "ability",
  "Fahrerseite": "Driver side",
  "fair": "fair",
  "falls": "if",
  "Fan": "Fan",
  "Fantasie": "fantasy",
  "färben": "color",
  "Fax": "Fax",
  "Fertiggericht": "ready meal",
  "Festanstellung": "Permanent position",
  "festkleben": "stick on",
  "festlegen": "set",
  "fett": "fat",
  "finanziell": "financial",
  "Finanzwesen": "Finance",
  "Firmensitz": "Company headquarters",
  "fix": "fix",
  "fleischfrei": "meat-free",
  "fleischlos": "meatless",
  "fließend": "fluent",
  "Flüchtling": "refugee",
  "Flug": "Flight",
  "Flugbegleiter/in": "Flight attendant",
  "Fluggast": "passenger",
  "Fluggesellschaft": "airline",
  "Föhn": "Hairdryer",
  "fordern": "demand",
  "fördern": "promote",
  "Formalität": "formality",
  "förmlich": "formal",
  "Formulierung": "Formulation",
  "Förster/in": "Forester",
  "Fortbildung": "Further training",
  "Fotokopie": "Photocopy",
  "Freiwillige": "Volunteers",
  "Fremdsprache": "Foreign language",
  "Freude": "joy",
  "Freundeskreis": "circle of friends",
  "Frieden": "Peace",
  "friedlich": "peaceful",
  "Frist": "deadline",
  "fristgerecht": "on time",
  "fristlos": "without notice",
  "Frisur": "hairstyle",
  "Frust": "frustration",
  "frustriert": "frustrated",
  "führen": "lead",
  "Führungszeugnis": "Certificate of good conduct",
  "furchtbar": "terrible",
  "Fußballclub": "football club",
  "füttern": "feed",
  "Gang": "gear",
  "garantieren": "guarantee",
  "Gastarbeiter/in": "Guest worker",
  "Gate": "Gate",
  "Gebrauchtwagen": "Used cars",
  "Gedanke": "thought",
  "Geduld": "Patience",
  "geduldig": "patiently",
  "Gefühl": "feeling",
  "Gegenstand": "subject",
  "Gegenvorschlag": "Counterproposal",
  "Gegner/in": "opponent",
  "Gehalt": "Salary",
  "Gehaltsvorstellung": "Salary expectations",
  "Gemeinsamkeit": "Commonality",
  "Gemeinschaftsraum": "Common room",
  "Gemüsehändler/in": "Greengrocer",
  "Gepäck": "Luggage",
  "Gepäckausgabe": "Baggage claim",
  "Gepäckband": "Baggage carousel",
  "Geruch": "smell",
  "Geschäftsführer/in": "Managing Director",
  "Geschäftsführung": "Management",
  "Geschmack": "taste",
  "gesetzlich": "legal",
  "Gesundheitszeugnis": "Health certificate",
  "Getreide": "Cereals",
  "gewährleisten": "ensure",
  "Gewohnheit": "habit",
  "Gewürz": "spice",
  "giftig": "poisonous",
  "gleichzeitig": "at the same time",
  "glutenfrei": "gluten free",
  "Golf": "Golf",
  "Grenze": "border",
  "gründen": "establish",
  "grundsätzlich": "basically",
  "Gutschein": "Voucher",
  "Haftpflicht": "Liability",
  "Haftpflichtversicherung": "Liability insurance",
  "Hagel": "Hail",
  "Halbpension": "Half board",
  "hämmern": "hammer",
  "Handball": "Handball",
  "Handgepäck": "Hand luggage",
  "Handlung": "plot",
  "Handwerker/in": "craftsman",
  "hart": "hard",
  "Hartweizen": "durum wheat",
  "Haselnuss": "hazelnut",
  "häufig": "often",
  "Hauptgrund": "Main reason",
  "Hauptstadt": "Capital",
  "Haushalt": "household",
  "Heimat": "Homeland",
  "Heimweh": "Homesickness",
  "heizen": "heat",
  "Heizkosten": "Heating costs",
  "Herausforderung": "Challenge",
  "herkommen": "come here",
  "Herkunftsland": "Country of origin",
  "herstellen": "produce",
  "Herstellung": "Manufacturing",
  "Herz": "heart",
  "hierher": "here",
  "hilfsbereit": "helpful",
  "historisch": "historical",
  "Hochwasser": "Flood",
  "Hörer/in": "listener",
  "Horrorfilm": "Horror film",
  "Hostel": "Hostel",
  "Hügel": "hill",
  "Hülsenfrucht": "legume",
  "hygienisch": "hygienic",
  "Impressum": "Imprint",
  "indem": "by",
  "individuell": "individually",
  "Industrie": "Industry",
  "industriell": "industrial",
  "Inlineskaten": "Inline skating",
  "innerhalb": "within",
  "insofern": "in this respect",
  "Instandhaltung": "Maintenance",
  "Institution": "institution",
  "intern": "internal",
  "inzwischen": "meanwhile",
  "irgendwann": "at some point",
  "irgendwelche": "any",
  "irgendwer": "anyone",
  "irgendwie": "somehow",
  "jahrelang": "for years",
  "Jahrhundert": "century",
  "Jahrzehnt": "decade",
  "Jobbezeichnung": "Job title",
  "Jude/Jüdin": "Jew/Jewess",
  "Jugendherberge": "Youth hostel",
  "Kaffeefilter": "Coffee filter",
  "Kamm": "comb",
  "Kandidat/in": "candidate",
  "Kaskoversicherung": "Comprehensive insurance",
  "Katalog": "Catalog",
  "Kauf": "purchase",
  "Kaufbestätigung": "Purchase confirmation",
  "Käufer/in": "Buyer",
  "Kaufvertrag": "Purchase agreement",
  "kaum": "hardly",
  "Kilometer": "kilometers",
  "Kindheit": "childhood",
  "kippen": "tilt",
  "klettern": "climb",
  "Klima": "Climate",
  "Klimawandel": "Climate change",
  "klug": "clever",
  "Kochbuch": "Cookbook",
  "Kofferraum": "trunk",
  "komfortabel": "comfortable",
  "Kommentator/in": "Commentator",
  "Kommissar/in": "Commissioner",
  "Kommunikationsstärke": "Communication skills",
  "kommunikativ": "communicative",
  "Komödie": "Comedy",
  "Konferenzraum": "Conference room",
  "Konflikt": "Conflict",
  "König/in": "King/in",
  "Konservendose": "tin can",
  "Kontaktdaten": "Contact details",
  "Kopie": "Copy",
  "Kopierer": "Copier",
  "korrekt": "correct",
  "Kosmetik": "Cosmetics",
  "krachen": "crash",
  "Kratzer": "Scratches",
  "Krieg": "war",
  "Kriegsende": "End of war",
  "Krimi": "Crime",
  "Krippe": "crib",
  "Kritiker/in": "Critic",
  "kulinarisch": "culinary",
  "kümmern": "care",
  "Kundenbefragung": "Customer survey",
  "kundenfreundlich": "customer friendly",
  "Kündigung": "Termination",
  "Kunststoff": "Plastic",
  "kuscheln": "cuddle",
  "Lage": "Location",
  "Lager": "Warehouse",
  "Lagerfeuer": "Campfire",
  "laktosefrei": "lactose free",
  "landen": "land",
  "Langeweile": "Boredom",
  "langfristig": "long term",
  "Lärm": "noise",
  "Laune": "Mood",
  "Lautsprecherdurchsage": "Loudspeaker announcement",
  "lebhaft": "lively",
  "Leichtathletik": "Athletics",
  "leiden": "suffer",
  "Leine": "leash",
  "leistungsgerecht": "performance-related",
  "leiten": "guide",
  "lenken": "direct",
  "Leuchtturm": "Lighthouse",
  "Lieblingsbeschäftigung": "Favorite activity",
  "lieferbar": "available",
  "Lieferbedingung": "Delivery condition",
  "Lieferung": "Delivery",
  "lohnen": "worthwhile",
  "Luft": "air",
  "luftdurchlässig": "air permeable",
  "lüften": "ventilate",
  "Magazin": "Magazine",
  "Manager/in": "Manager",
  "Mannschaft": "team",
  "Maschinenbau": "Mechanical engineering",
  "Massentierhaltung": "Factory farming",
  "massiv": "massive",
  "Matratze": "mattress",
  "Mauer": "wall",
  "Mauerbau": "Building a wall",
  "Mauerfall": "Fall of the wall",
  "meckern": "complain",
  "Medizin": "Medicine",
  "Meerblick": "Sea view",
  "Meerschweinchen": "Guinea pig",
  "Mehrheit": "Majority",
  "Mehrkosten": "Additional costs",
  "mehrmals": "several times",
  "meistern": "master",
  "Mentalität": "mentality",
  "merken": "remember",
  "Metall": "metal",
  "Mieterhöhung": "Rent increase",
  "Mietspiegel": "Rent index",
  "Mietvertrag": "Rental agreement",
  "Migration": "Migration",
  "Milchkarton": "Milk carton",
  "Milchzucker": "lactose",
  "Million": "million",
  "Millionär/in": "millionaire",
  "Minderheit": "minority",
  "mitdenken": "think along",
  "miteinander": "with each other",
  "miterleben": "witness",
  "mitreden": "have a say",
  "Mittelfeld": "Midfield",
  "mittelständisch": "medium-sized",
  "mitten": "middle",
  "Moderation": "Moderation",
  "Modernisierung": "Modernization",
  "moralisch": "moral",
  "Mord": "Murder",
  "motiviert": "motivated",
  "Motor": "engine",
  "Motorhaube": "bonnet",
  "Motorradfahrer/in": "Motorcyclist",
  "Mülltonne": "garbage can",
  "Mülltrennung": "Waste separation",
  "musikalisch": "musically",
  "Muttersprache": "native language",
  "nachdem": "after",
  "nachdenken": "think",
  "nachdenklich": "thoughtful",
  "Nachkriegszeit": "Post-war period",
  "Nachnahme": "Cash on delivery",
  "nachsehen": "look",
  "Nachteil": "Disadvantage",
  "Nährstoff": "nutrient",
  "Nahrungsmittel": "Food",
  "naschen": "snack",
  "Nationalsozialismus": "National Socialism",
  "NATO": "NATO",
  "Naturkatastrophe": "Natural disaster",
  "Naturprodukt": "Natural product",
  "Nebel": "Fog",
  "nebenbei": "by the way",
  "neblig": "foggy",
  "neugierig": "curious",
  "Neuwagen": "New car",
  "Niederlage": "Defeat",
  "Niveau": "level",
  "Notunterkunft": "Emergency shelter",
  "Nummernschild": "license plate",
  "Nuss": "Nut",
  "objektiv": "objectively",
  "Obstschale": "Fruit bowl",
  "obwohl": "although",
  "offen": "open",
  "offenbar": "apparently",
  "Öffnung": "Opening",
  "Oldtimer": "Classic cars",
  "Onlineeinkauf": "Online shopping",
  "Onlineshop": "Online shop",
  "Onlineshopping": "Online shopping",
  "optimistisch": "optimistic",
  "Original": "Original",
  "Paket": "package",
  "Paketbote": "Parcel courier",
  "Paketdienst": "Parcel service",
  "Papiermüll": "Paper waste",
  "Pappe": "cardboard",
  "Paradies": "Paradise",
  "parken": "park",
  "Parklücke": "parking space",
  "Passagier/in": "Passenger",
  "Passkontrolle": "Passport control",
  "PC": "PC",
  "Personenschaden": "Personal injury",
  "Pflegehelfer/in": "Nursing assistant",
  "Pflegekraft": "Caregiver",
  "Phase": "phase",
  "Picknick": "Picnic",
  "Pilotenstreik": "Pilots' strike",
  "Planet": "Planet",
  "Plastik": "Plastic",
  "politisch": "political",
  "Pool": "Pool",
  "Porto": "Postage",
  "portofrei": "postage free",
  "Portokosten": "Postage costs",
  "Posteingang": "Inbox",
  "präsentieren": "present",
  "Privatnummer": "Private number",
  "Probezeit": "Probationary period",
  "problemlos": "problem-free",
  "produzieren": "produce",
  "Protest": "protest",
  "protestieren": "protest",
  "PS": "P.S",
  "Qualifikation": "Qualification",
  "Qualität": "Quality",
  "Quark": "Quark",
  "quietschen": "squeak",
  "Quizshow": "Quiz show",
  "Radrennen": "Cycling race",
  "Rangliste": "Ranking",
  "rasieren": "shave",
  "Rätsel": "Puzzles",
  "rechtzeitig": "in time",
  "recyceln": "recycle",
  "reduzieren": "reduce",
  "regeln": "regulate",
  "Regierung": "Government",
  "regulieren": "regulate",
  "Regulierung": "Regulation",
  "Reifen": "tires",
  "Reihe": "row",
  "Reinigungsfirma": "Cleaning company",
  "Reinigungsvertrag": "Cleaning contract",
  "Reisebüro": "Travel agency",
  "Reiseplan": "Travel plan",
  "Reiseplanung": "Travel planning",
  "reiten": "ride",
  "Reklamation": "Complaint",
  "Reportage": "Reportage",
  "Reporter/in": "Reporter",
  "Republik": "Republic",
  "Retoure": "Return",
  "Retourenschein": "Return slip",
  "retten": "save",
  "Richter/in": "Judge",
  "romantisch": "romantic",
  "Rücklicht": "Rear light",
  "Rückscheibe": "Rear window",
  "Rücksendung": "Return",
  "Rücksicht": "Consideration",
  "rückwärts": "backwards",
  "Ruhezeit": "Rest time",
  "Runde": "round",
  "Russlanddeutsche": "Russian Germans",
  "Sachbearbeiter/in": "clerk",
  "Sachschaden": "Property damage",
  "Sack": "sack",
  "sammeln": "collect",
  "Sammelstelle": "Collection point",
  "sauber": "clean",
  "Sauberkeit": "Cleanliness",
  "sauer": "sour",
  "Schaden": "Damage",
  "Schadensfall": "Damage event",
  "schädigen": "damage",
  "schädlich": "harmful",
  "Schadstoff": "pollutant",
  "schalten": "switch",
  "Schalter": "Switch",
  "Scheibe": "disc",
  "Scheinwerfer": "Headlight",
  "Schiedsrichter": "Referee",
  "schießen": "shoot",
  "Schläger": "Thug",
  "Schlange": "Snake",
  "schmutzig": "dirty",
  "schneiden": "cut",
  "Schreiben": "Write",
  "schützen": "protect",
  "schwingen": "swing",
  "Seifenoper": "Soap opera",
  "seitdem": "since then",
  "Selbstständige": "Self-employed people",
  "selbstverständlich": "of course",
  "senden": "send",
  "Sendung": "broadcast",
  "Seniorenheim": "retirement home",
  "senken": "lower",
  "Serie": "series",
  "Shopping": "Shopping",
  "siegen": "win",
  "Sieger/in": "winner",
  "Sinn": "sense",
  "sinnlos": "pointless",
  "sinnvoll": "makes sense",
  "Skisport": "Ski sports",
  "Soap": "Soap",
  "Solarenergie": "Solar energy",
  "Sondermüll": "Hazardous waste",
  "Sonnenschein": "Sunshine",
  "Sonnenschirm": "parasol",
  "Sonnenterrasse": "Sun terrace",
  "Sonnenuntergang": "Sunset",
  "Sorge": "Worry",
  "sortieren": "sort",
  "soweit": "so far",
  "spannend": "exciting",
  "sparsam": "economical",
  "Speise": "food",
  "Sperrmüll": "Bulky waste",
  "spezialisieren": "specialize",
  "Spieler/in": "player",
  "Spielfilm": "Feature film",
  "Sportwagen": "Sports car",
  "Sprachnachweis": "Language certificate",
  "Staat": "State",
  "Staatsgründung": "Founding of the state",
  "Stadion": "Stadium",
  "Statistik": "Statistics",
  "stattfinden": "take place",
  "Stellenanzeige": "Job advertisement",
  "Stern": "star",
  "Steuerberater": "Tax advisor",
  "Steuerberatungsbüro": "Tax advisory office",
  "stinken": "stink",
  "stinksauer": "pissed off",
  "Stipendium": "Scholarship",
  "stören": "disturb",
  "Stoßstange": "bumper",
  "Straßenrand": "roadside",
  "Straßenverkehr": "Road traffic",
  "Streichholz": "Matchstick",
  "streiken": "strike",
  "streiten": "argue",
  "Strom": "Electricity",
  "Stromanbieter": "Electricity provider",
  "Stromkosten": "Electricity costs",
  "Studie": "Study",
  "Sturm": "Storm",
  "Tagesablauf": "Daily routine",
  "Talkshow": "Talk show",
  "Taschenlampe": "Flashlight",
  "Taschenmesser": "Pocket knife",
  "tatsächlich": "actually",
  "Teamfähigkeit": "Teamwork skills",
  "Teilkaskoversicherung": "Partial insurance",
  "Teilung": "division",
  "Telekommunikation": "Telecommunications",
  "Terminkalender": "Appointment calendar",
  "Tiefkühlpizza": "Frozen pizza",
  "tierisch": "animalistic",
  "Tierschutz": "Animal protection",
  "Tor": "Gate",
  "Torwart/in": "Goalkeeper",
  "total": "totally",
  "Tote": "dead",
  "traditionsreich": "rich in tradition",
  "traumhaft": "fantastic",
  "Trend": "trend",
  "treu": "faithful",
  "Trinkwasser": "Drinking water",
  "tropfen": "drip",
  "trüb": "cloudy",
  "Tsunami": "Tsunami",
  "Turm": "tower",
  "übereinstimmen": "match",
  "übergeben": "handed over",
  "überglücklich": "overjoyed",
  "überlegen": "consider",
  "übernachten": "stay overnight",
  "Übernachtung": "Overnight stay",
  "überraschen": "surprise",
  "Überschwemmung": "flooding",
  "übersetzen": "translate",
  "Übersetzung": "Translation",
  "Übersetzungsbüro": "Translation agency",
  "Überstunde": "Overtime",
  "Übertragung": "Transmission",
  "überzeugen": "convince",
  "üblich": "usual",
  "umdrehen": "turn around",
  "umfallen": "fall over",
  "Umgang": "handling",
  "Umgebung": "Environment",
  "umgehen": "deal with",
  "umgehend": "immediately",
  "Umschulung": "Retraining",
  "umso": "all the more",
  "umweltfreundlich": "environmentally friendly",
  "Umweltschutz": "Environmental protection",
  "Umweltverschmutzung": "Pollution",
  "unbefristet": "unlimited",
  "unentschieden": "undecided",
  "Unfall": "Accident",
  "Unfallgefahr": "Danger of accidents",
  "ungeduldig": "impatient",
  "ungesund": "unhealthy",
  "unglaublich": "incredible",
  "unnötig": "unnecessary",
  "Unrecht": "Injustice",
  "Unterhaltung": "Entertainment",
  "Unternehmen": "Company",
  "unverbindlich": "non-binding",
  "Unwetter": "Storm",
  "Urlaubstag": "vacation day",
  "Urteil": "Judgment",
  "vegan": "vegan",
  "Veganer/in": "Vegan",
  "verabreden": "arrange",
  "verändern": "change",
  "verärgert": "upset",
  "Verbrauch": "consumption",
  "Verbraucher/in": "Consumer",
  "verdrängen": "repress",
  "vereinbar": "compatible",
  "vereinigen": "unite",
  "verfolgen": "pursue",
  "vergleichbar": "comparable",
  "Vergütung": "Compensation",
  "verhaften": "arrest",
  "verlängern": "extend",
  "verlassen": "leave",
  "verlaufen": "run",
  "verletzen": "hurt",
  "Verlierer/in": "loser",
  "vermischen": "mix",
  "vermissen": "miss",
  "verpacken": "pack",
  "verpflichten": "oblige",
  "verreisen": "travel",
  "Versand": "Shipping",
  "Versandkosten": "Shipping costs",
  "versandkostenfrei": "free shipping",
  "Versandkostenpauschale": "Flat rate shipping fee",
  "verschieben": "move",
  "verschmutzen": "pollute",
  "verschwenden": "waste",
  "Verschwendung": "Waste",
  "versehentlich": "accidentally",
  "versenden": "send",
  "versichern": "insure",
  "Versicherungsberater/in": "Insurance advisor",
  "Versicherungsschutz": "Insurance coverage",
  "versorgen": "supply",
  "versprechen": "promise",
  "Verständnis": "understanding",
  "Verstärkung": "Reinforcement",
  "Verstoß": "Violation",
  "verstoßen": "violated",
  "vertragen": "tolerated",
  "Vertragsende": "End of contract",
  "Vertragsnummer": "Contract number",
  "verursachen": "cause",
  "verurteilen": "condemn",
  "verwerten": "utilize",
  "Verzehr": "consumption",
  "verzichten": "forego",
  "Visum": "Visa",
  "völlig": "completely",
  "Vollkaskoversicherung": "Fully comprehensive insurance",
  "voraussichtlich": "expected",
  "vorbeigehen": "pass by",
  "vorher": "before",
  "vorhersagen": "predict",
  "vorschreiben": "prescribe",
  "vorsichtig": "carefully",
  "wahr": "true",
  "wahrscheinlich": "probably",
  "Wanderer": "Hiker",
  "Wandertour": "Hiking tour",
  "Ware": "goods",
  "Warenkorb": "Shopping cart",
  "Wärme": "Warmth",
  "Waschraum": "Washroom",
  "wasserdicht": "waterproof",
  "Wasserhahn": "faucet",
  "wegfahren": "drive away",
  "wegräumen": "put away",
  "wegschmeißen": "throw away",
  "wegwerfen": "throw away",
  "Weise": "way",
  "weitergehen": "move on",
  "weiterhelfen": "help",
  "Weiterleitung": "Forwarding",
  "Weltall": "Space",
  "Weltmeisterschaft": "World Cup",
  "Werktag": "working day",
  "Werkzeug": "tool",
  "Wert": "Value",
  "Wertstoff": "Recyclable material",
  "weshalb": "why",
  "wetterfest": "weatherproof",
  "widerrufen": "revoked",
  "Widerrufsrecht": "Right of withdrawal",
  "Widerspruch": "contradiction",
  "wiedervereinigen": "reunite",
  "Wiedervereinigung": "Reunion",
  "Wind": "wind",
  "Windel": "diaper",
  "Windschutzscheibe": "windshield",
  "Wirbelsturm": "Hurricane",
  "wohlfühlen": "feel good",
  "Wohnwagen": "Caravan",
  "Wolke": "cloud",
  "Wurst": "Sausage",
  "wütend": "angry",
  "Zahlung": "Payment",
  "zappen": "zap",
  "zaubern": "conjure up",
  "Zeichentrickfilm": "cartoon",
  "zeitlich": "temporally",
  "Zeitmangel": "Lack of time",
  "Zeitpunkt": "point in time",
  "Zeitraum": "period",
  "Zeitungsbericht": "Newspaper report",
  "Zeitverschwendung": "Waste of time",
  "Zelt": "tent",
  "zerschlagen": "smashed",
  "zerstören": "destroy",
  "Zerstörung": "Destruction",
  "Ziel": "Target",
  "ziemlich": "quite",
  "Zigarettenkippe": "Cigarette butt",
  "Zimmerlautstärke": "Room volume",
  "Zoll": "inches",
  "zudrehen": "turn closed",
  "zufällig": "random",
  "zugeben": "admit",
  "zügig": "quickly",
  "zulassen": "allow",
  "zumachen": "close",
  "zunehmen": "increase",
  "zurückfahren": "drive back",
  "zurückkehren": "return",
  "zurücklassen": "leave behind",
  "zurückschicken": "send back",
  "zurücksenden": "send back",
  "zurücktreten": "resign",
  "Zusammenarbeit": "Collaboration",
  "zusammenarbeiten": "work together",
  "Zusammenleben": "Living together",
  "zusammenstellen": "put together",
  "zusammenstoßen": "collide",
  "zusätzlich": "additionally",
  "Zusatzqualifikation": "Additional qualification",
  "Zusatzstoff": "additive",
  "Zusatzversicherung": "Additional insurance",
  "Zuschauer/in": "spectator",
  "Zuschlag": "Surcharge",
  "zustellen": "deliver",
  "zustimmen": "agree",
  "Zutritt": "Access",
  "Zuverlässigkeit": "Reliability"
};
